### ISSUE TITLE
TypeError when running macht on Python 3.7.6

### ISSUE THREAD

**Issue by sridhar-vadlamani-ck** [rolfmorel/macht#3]
```
Traceback (most recent call last):
  File "/usr/local/bin/macht", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/macht/term/main.py", line 132, in main
    key = term.inkey(_intr_continue=False)
TypeError: inkey() got an unexpected keyword argument '_intr_continue'
```

I'm on Mac 10.14

**Comment by jquast** [comment]
Just delete the argument, “_intr_continue=False” from that line of code, and it should work. I’ll make a PR for @rolfmorel later

**Comment by jquast** [comment]
https://github.com/jquast/blessed/releases/tag/1.17.0

> deprecated: using argument _intr_continue to method kbhit, behavior is as
though such value is always True since 1.9.

**Comment by jquast** [comment]
This was fixed 4 years ago, @rolfmorel just needs to publish it to pypi.

https://github.com/rolfmorel/macht/commit/aac049d1902e15545a2a957040c66c0a7a81b96e

**Comment by msr8** [comment]
@sridhar-vadlamani-ck I had the same problem, but when I built from source it worked. All I had to do was

```shell
git clone https://github.com/rolfmorel/macht
cd macht
python3 setup.py install
```

**Comment by markuspi** [comment]
Same problem for me. Installing directly from git using pip also works like a charm:
```bash
pip install git+https://github.com/rolfmorel/macht.git
```
