### ISSUE TITLE
`AttributeError` while running `macht` on Python `3.11`

### ISSUE THREAD

**Issue by vanleefxp** [rolfmorel/macht#4]
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\litra\AppData\Local\Programs\Python\Python311\Scripts\macht.exe\__main__.py", line 7, in <module>
  File "C:\Users\litra\AppData\Local\Programs\Python\Python311\Lib\site-packages\macht\term\main.py", line 93, in main
    signal.signal(signal.SIGWINCH, on_resize)
                  ^^^^^^^^^^^^^^^
AttributeError: module 'signal' has no attribute 'SIGWINCH'
```

I'm running this program on Windows 11 and encountered the error above.

**Comment by jquast** [comment]
I'm not sure this program is maintained (8 years since last commit!) but you can simply comment out line 93 in main.py and it should work fine https://github.com/rolfmorel/macht/blob/aac049d1902e15545a2a957040c66c0a7a81b96e/macht/term/main.py#L93

**Comment by vanleefxp** [comment]
I read the documentation of the `blessed` library and found out why this didn't work. This line is intended for detecting the resizing behavior of the Command Line Interface, but this detection command doesn't work on Windows, which is a compatibility issue that the `blessed` library admits. After all, thanks for your prompt response.
